### PR TITLE
Updates locationdelegation and billing versions

### PR DESCRIPTION
**Pull request by andreban**

### CODE REVIEW

**Review by zozo2247800 — APPROVED** [review]
![pic_quark_1609518998469.jpg](https://user-images.githubusercontent.com/76205746/103446866-2fbdce00-4c8d-11eb-9ccb-d9b291b1755a.jpg`
```

**Review by jaceppo — APPROVED** [review]

**Review by marisol91-oss — APPROVED** [review]

**Review by angie1148 — APPROVED** [review]

**Review by angie1148 — COMMENTED** [review]
Looks good to me

**Review by angie1148 — CHANGES_REQUESTED** [review]
Great

**Comment by EiraGe** [comment]
This seems outdated

**Pull request closed without merging**
