### PR TITLE
updated the latest library version in readme

### PR DESCRIPTION
**Pull request by build3r**
Updated the library version in readme.
User might not see latest release and end up using the old library version mentioned in readme.

### CODE REVIEW

**Review by PEConn — APPROVED** [review]
Thanks for this!

**Comment by PEConn** [comment]
You'll need to sign the CLA before we can merge this - see the details of the failing check.

**Comment by build3r** [comment]
I just finished signing the CLA, the pull auto update?

**Comment by build3r** [comment]
Ok, had to trigger a rescan. Its done now.

**Pull request merged**
